# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs

#### using anchors
default: &dockerImage
  docker:
  - image: circleci/node:13.8.0


jobs:
  build:
    << : *dockerImage
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
          paths:
              - node_modules
      - run:
          name: Running lint
          command: npm run lint
  test:
    << : *dockerImage
    steps:
      - checkout  
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}  #### Restores from the cache
      - run:
          name: Install node dependencies ### checks if node_modules exist in cache to speed up process
          command: "[ ! -d node_modules ] && npm ci --loglevel warn --yes || echo package.json and package-lock.json unchanged. Using cache."
      - run: 
          name: Running test
          command: npm run test
  analyze:
    << : *dockerImage
    steps:
      - checkout
      - run: 
          name:  Static code analysis
          command: npm audit
workflows:
  react_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze: 
          requires:
            - test